config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'

  get 'logins/logout'

  resources :logins do
  	member do
  		get :delete
  	end
  end

  resources :clients do
    member do
      get :delete
    end
  end

  resources :chats do
    member do
      get :delete
    end
  end

  resources :messages do
    member do
      get :delete
    end
  end


  #get 'clients/new'

  #get 'clients/create'

  #get 'clients/show'

  #get 'registrations/new'

  #get 'registrations/create'

  #get 'registrations/show'

  #get 'logins/new'

  #get 'logins/create'

  #get 'logins/show'

  #get 'client/home'

  #get 'client/chats'

  #get 'login/login'

  #get 'registration/register'

  #post 'logins/auth_login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  #To display the login form
  def new
  	@client = Client.new
    @page_title = "Login"
  end

  #To authenticate login
  def create

    if params[:client][:username].present? && params[:client][:password].present?
  	  
      @login_details = Client.login_check(params[:client][:username]).first

  	  if @login_details && @login_details.authenticate(params[:client][:password])
        session[:user_id] = @login_details.id
        flash[:notice] = "You are now logged in"
		    redirect_to(client_path(@login_details.id))
	    else
		    flash[:error] = 'Invalid Username or Password'
		    redirect_to('/')
	    end
    else
      flash[:error] = "Please provide both username and password"
      redirect_to('/')
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to('/')
  end


private

  def login_params
    params.require(:client).permit(:username, :password)
  end

end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<div class="login">
  <h2>Login</h2>

  <%= form_for(@client, :url => logins_path, :method => 'post') do |f| %>

    <table summary="Login form fields">
      <tr>
        <th>Username</th>
        <td><%= f.text_field(:username) %></td>
      </tr>
        <th>Password</th>
        <td><%= f.password_field(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Login") %>
      <%= link_to("Register new client", new_client_path) %>
    </div>

  <% end %>
</div>

app/views/logins/show.html.erb
<h1>Logins#show</h1>
<p>Find me in app/views/logins/show.html.erb</p>