config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'

  get 'logins/logout'

  resources :logins do
  	member do
  		get :delete
  	end
  end

  resources :clients do
    member do
      get :delete
    end
  end

  resources :chats do
    member do
      get :delete
    end
  end

  resources :messages do
    member do
      get :delete
    end
  end


  #get 'clients/new'

  #get 'clients/create'

  #get 'clients/show'

  #get 'registrations/new'

  #get 'registrations/create'

  #get 'registrations/show'

  #get 'logins/new'

  #get 'logins/create'

  #get 'logins/show'

  #get 'client/home'

  #get 'client/chats'

  #get 'login/login'

  #get 'registration/register'

  #post 'logins/auth_login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord

	has_secure_password

	has_many :chats

	scope :login_check, lambda { |username| where(:username => username)}

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :first_name, :presence => true, :length => { :maximum => 40 }
  	
  	validates :last_name, :presence => true, :length => { :maximum => 40 }
  	
  	validates :age, :presence => true, :numericality => true

  	validates :username, :presence => true, :length => { :maximum => 25, :minimum => 4 }, :uniqueness => true
  	
  	validates :password, :presence => true

  	validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    :format => EMAIL_REGEX,
					:uniqueness => true                    

	validates :client_type, :presence => true, :inclusion => {:in => ['USER', 'TRAINER', 'ADMIN']}

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :confirm_logged_in, :only => [:show]

  #Display the registration form
  def new
  	@client = Client.new
    @page_title = "Registration"
  end

  #Save registration details
  def create
  	@client = Client.new(register_params)
  	if @client.save
  		flash[:notice] = "Client registered succesfully. You can login now."
  		redirect_to(new_login_path)
  	else
  		#flash[:error] = @client.errors.messages
		  render('new')
  	end
  end

  #show the client home page
  def show
    #puts(session[:user_id])
  	@client = Client.find_by_id(params[:id])
    @page_title = "Home"
    if @client.blank?
      redirect_to('/404.html')
    end
  end

  private

  def register_params
  	params.require(:client).permit(:first_name, :last_name, :age, :email, :client_type, :date_of_birth, :username, :password)
  end
  
  def confirm_logged_in
    if session[:user_id].blank?
      flash[:notice] = "Please log in"
      redirect_to('/')
    end
    if session[:user_id] != params[:id].to_i
      flash[:notice] = "You tried to view someone else's account. This is not allowed."
      params[:id] = session[:user_id]
      redirect_to(client_path(params[:id]))
    end
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/new.html.erb
<div class="registration">
  <h2>Registration</h2>

  <%= form_for(@client, :url => clients_path, :method => 'post') do |f| %>
    <%= show_error_messages(f.object) %>
    <table summary="Login form fields">
      <tr>
        <th>First Name</th>
        <td><%= f.text_field(:first_name) %></td>
      </tr>
      <tr>
        <th>Last Name</th>
        <td><%= f.text_field(:last_name) %></td>
      </tr>
      <tr>
        <th>Age</th>
        <td><%= f.text_field(:age) %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= f.text_field(:email) %></td>
      </tr>
      <tr>
        <th>Client Type</th>
        <td><%= f.select(:client_type, ['USER', 'TRAINER']) %></td>
      </tr>
      <tr>
        <th>Date of Birth</th>
        <td><%= f.date_select(:date_of_birth, :order => [:month, :day, :year], :start_year => 1970, :end_year => Time.now.year) %></td>
      </tr>
      <tr>
        <th>Username</th>
        <td><%= f.text_field(:username) %></td>
      </tr>
        <th>Password</th>
        <td><%= f.password_field(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Register") %>
      <%= link_to("Existing client login", new_login_path) %>
    </div>

  <% end %>
</div>

app/views/clients/show.html.erb
<div class="profile show">
  <h2>Welcome <%= @client.first_name %>!!!</h2>

  <table summary="Client detail view">
    <tr>
      <th>Name</th>
      <td><%= @client.first_name+" "+@client.last_name %></td>
    </tr>
    <tr>
      <th>Date of Birth</th>
      <td><%= @client.date_of_birth %></td>
    </tr>
    <tr>
      <th>Type</th>
      <td><%= @client.client_type %></td>
    </tr>
    <tr>
      <th>Age</th>
      <td><%= @client.age %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @client.email %></td>
    </tr>
  </table>

</div>

<%= link_to("See your chats", chat_path(@client.id)) %>