config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'

  get 'logins/logout'

  resources :logins do
  	member do
  		get :delete
  	end
  end

  resources :clients do
    member do
      get :delete
    end
  end

  resources :chats do
    member do
      get :delete
    end
  end

  resources :messages do
    member do
      get :delete
    end
  end


  #get 'clients/new'

  #get 'clients/create'

  #get 'clients/show'

  #get 'registrations/new'

  #get 'registrations/create'

  #get 'registrations/show'

  #get 'logins/new'

  #get 'logins/create'

  #get 'logins/show'

  #get 'client/home'

  #get 'client/chats'

  #get 'login/login'

  #get 'registration/register'

  #post 'logins/auth_login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
	
	belongs_to :client, {:foreign_key => "client1"}
	has_many :messages

	scope :chat_client1, lambda { |client_id| where(:client1 => client_id) }
	scope :chat_client2, lambda { |client_id| where(:client2 => client_id) }

	validates :client1, :presence => true, :numericality => true
	
	validates :client2, :presence => true, :numericality => true
	
	validates :num_messages, :presence => true, :numericality => true
end

app/models/client.rb
class Client < ApplicationRecord

	has_secure_password

	has_many :chats

	scope :login_check, lambda { |username| where(:username => username)}

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :first_name, :presence => true, :length => { :maximum => 40 }
  	
  	validates :last_name, :presence => true, :length => { :maximum => 40 }
  	
  	validates :age, :presence => true, :numericality => true

  	validates :username, :presence => true, :length => { :maximum => 25, :minimum => 4 }, :uniqueness => true
  	
  	validates :password, :presence => true

  	validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    :format => EMAIL_REGEX,
					:uniqueness => true                    

	validates :client_type, :presence => true, :inclusion => {:in => ['USER', 'TRAINER', 'ADMIN']}

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :confirm_logged_in

  def new
  	@message = Message.new(:message => "Hi! Let's chat.")
  	#for new chat
    @page_title = "New chat"
    @ecc, @chat_ids = existing_chat_details(params[:id])
    if @ecc.blank?
      exclude_client_id_string = params[:id]
    else
      exclude_client_id_string = @ecc + "," + params[:id]
    end
    @ncc = get_new_chat_clients(exclude_client_id_string)
    if @ncc.blank?
      @no_more_users_to_chat = "We couldn't find any more users to chat. Either you already have an existing chat with all of them or you are too lonely :P"
    end
    @sender_id = params[:id]
  end

  def create
    message = Message.new(chat_params)
    chat = Chat.new
    chat.client1 = message.sender
    chat.client2 = message.receiver
    chat.num_messages = 1
    if chat.save
      m = chat.messages << message
      if m.blank?
        chat.destroy
        flash[:error] = "Your message was not sent."
        redirect_to(new_chat_path(:id => message.sender))
      else
        #message sent successfully. Show chat page
        receiver = Client.find_by_id(message.receiver)
        receiver_name = receiver.first_name + " (" + receiver.client_type + ")"
        flash[:notice] = "Your chat with #{receiver_name} has started."
        redirect_to(edit_chat_path(m[0].chat_id))
      end
    else
      #Chat could not be saved successfully
      flash[:error] = "Your chat was not sent."
      redirect_to(new_chat_path(:id => message.sender))
    end

  end

  def show

    if session[:user_id] != params[:id].to_i
      flash[:notice] = "You are not allowed to view chat list of other clients."
      redirect_to(chat_path(session[:user_id]))
    end

    @page_title = "Your chats"
    #get the client ID comma separated string with which the currently logged in client
  	@client_ids, @chat_ids = existing_chat_details(params[:id])
    @user_id = params[:id]
  	if @client_ids.blank?
  		#show that no chat
  		@no_chat_message = "Sorry! We can't find any chat where you are involved."
  	else
  		#show chats. collect all client IDs with whom the user has chatted
      
      @chat_clients = Client.where("id IN (#{@client_ids})")
    end
  end

  def edit
    @chat_id = params[:id]
    @messages = Message.get_chat_messages(@chat_id)
    @curr_user_id = session[:user_id]

    @chat_client_name = {}
    @chat_client_name[@curr_user_id] = Client.find_by_id(@curr_user_id).first_name

    @chat_details = Chat.find_by_id(@chat_id)
    
    if @curr_user_id == @chat_details.client1
      @chat_client_name[@chat_details.client2] = Client.find_by_id(@chat_details.client2).first_name
      @other_user_id = @chat_details.client2
    else
      @chat_client_name[@chat_details.client1] = Client.find_by_id(@chat_details.client1).first_name
      @other_user_id = @chat_details.client1
    end
    @page_title = "Your chat with #{@chat_client_name[@other_user_id]}"
    @msg = Message.new
  end

  private

  def chat_params
    params.require(:message).permit(:receiver, :message, :sender)
  end

  def get_new_chat_clients(existing_client_str)
    ncc = Client.where("id NOT IN (#{existing_client_str})")
    ncc
  end

  def existing_chat_details(client_id)
    chat_list_1 = Chat.select(:client2, :id).chat_client1(client_id)
    chat_list_2 = Chat.select(:client1, :id).chat_client2(client_id)

    @chat_ids = {}

    chat_list_1.each do |c|
      (@c_ids ||= []) << c.client2
      @chat_ids[c.client2] = c.id
    end
    chat_list_2.each do |c|
      (@c_ids ||= []) << c.client1
      @chat_ids[c.client1] = c.id
    end

    client_ids = ''
    
    if !@c_ids.blank?
      client_ids = @c_ids.uniq.join(",")
    end
    
    return client_ids, @chat_ids
  end

  def confirm_logged_in
    unless session[:user_id]
      flash[:notice] = "Please log in"
      redirect_to('/')
    end
  end

end

app/helpers/chats_helper.rb
module ChatsHelper
	

	
end

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/edit.html.erb
<%= link_to("<<<< Home", client_path(@curr_user_id)) %><br><br>

<div style="width: 700px; margin: 0 auto;">
Your chat with <%= @chat_client_name[@other_user_id] %>
</div>
<div style="width: 700px; height: 500px; margin: 0 auto; border-style: solid;">
<% @messages.each do |m| %>
	<% if m.sender == @curr_user_id %>
		<div style="float:right;">
			You: <%= m.message %>
		</div>
	<% else %>
		<div style="float:left;">
			<%= @chat_client_name[m.sender] + ": " + m.message %>
		</div>
	<% end %>
	<br><hr>
<% end %>

</div>

<div style="width: 700px; margin: 0 auto;">
<%= form_for(@msg, :url => messages_path, :method => 'post') do |f| %>

    <table summary="New chat form fields">
        <th>Message</th>
        <td><%= f.text_area(:message, :size => "50x2") %></td>
      </tr>
      <%= f.hidden_field(:sender, value: @curr_user_id) %>
      <%= f.hidden_field(:receiver, value: @other_user_id) %>
      <%= f.hidden_field(:chat_id, value: @chat_id) %>
    </table>

    <div class="form-buttons">
      <%= f.submit("Send chat") %>
    </div>

  <% end %>
</div>

app/views/chats/new.html.erb
<%= link_to("<< Go Back", chat_path(@sender_id)) %><br><br>

<div class="new_chat">

  <% if @no_more_users_to_chat.present? %>
  <div>
    <%= @no_more_users_to_chat %> <br>
  </div>

  <% else %>

  <h2>Start a new chat</h2>

  <%= form_for(@message, :url => chats_path, :method => 'post') do |f| %>

    <table summary="New chat form fields">
      <tr>
        <th>Chat with: </th>
        <td><%= f.select(:receiver, @ncc.map {|c| [c.first_name+" ("+c.client_type+")", c.id]}) %>
          <%= f.hidden_field(:sender, value: @sender_id) %></td>

      </tr>
        <th>Message</th>
        <td><%= f.text_area(:message) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Send chat") %>
    </div>

  <% end %>
  
  <% end %>
</div>

app/views/chats/show.html.erb
<%= link_to("<< Go Back", client_path(@user_id)) %><br>
<br>
<% if !@no_chat_message.blank? %>
    <div >
     <%= @no_chat_message %>
    </div><br>
<% end %>

<% if !@chat_clients.blank? %>
    <div >
    <h4>You have chatted with following clients in the past. You can click on any one of them and continue.</h4>
    <hr>
    <% @chat_clients.each do |cc| %>
    
    <div>
    	<% name = cc.first_name+" "+cc.last_name+" ("+cc.client_type+")" %>
    	<%= link_to(name, edit_chat_path(@chat_ids[cc.id])) %>
    </div>
    <hr>
    <% end %>

    </div>
<% end %>
<br><br>
<div class="new_chat_button">
	You can start a new chat <%= link_to("here", new_chat_path(:id => @user_id)) %>
</div>