config/routes.rb
Rails.application.routes.draw do

  root 'logins#new'

  get 'logins/logout'

  resources :logins do
  	member do
  		get :delete
  	end
  end

  resources :clients do
    member do
      get :delete
    end
  end

  resources :chats do
    member do
      get :delete
    end
  end

  resources :messages do
    member do
      get :delete
    end
  end


  #get 'clients/new'

  #get 'clients/create'

  #get 'clients/show'

  #get 'registrations/new'

  #get 'registrations/create'

  #get 'registrations/show'

  #get 'logins/new'

  #get 'logins/create'

  #get 'logins/show'

  #get 'client/home'

  #get 'client/chats'

  #get 'login/login'

  #get 'registration/register'

  #post 'logins/auth_login'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp: <%= @page_title || "Welcome" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <% if !flash[:notice].blank? %>
    <div class="notice">
     <%= flash[:notice] %>
    </div>
  <% end %>

  <% if !flash[:error].blank? %>
    <div class="error" style="color:red;">
        <%= flash[:error] %>
    </div>
  <% end %>

  <% if !session[:user_id].blank? %>
    <div style="float:right;">
     <%= link_to('Logout', logins_logout_path) %>
    </div>
  <% end %>

    <%= yield %>
  </body>
</html>